version: "3"
services:
    kv:
        image: kv:latest
        build:
            dockerfile: Dockerfile
            context: .
        environment:
            REDIS_URL: redis://redis:6379/0
        ports:
            - "80:80"

    redis:
        image: redis
